### ISSUE TITLE
Random floating images of items after blowing up rocks.

### ISSUE THREAD

**Issue by DeadOblivion78** [PhillZitt/BetterBombs#8] opened 2021-02-27 19:47 UTC
![Screenshot (134)](https://user-images.githubusercontent.com/12665798/109398378-e63ed780-78f9-11eb-8bc8-35da7e0982d1.png)
![Screenshot (135)](https://user-images.githubusercontent.com/12665798/109398380-e6d76e00-78f9-11eb-8620-070633279fb7.png)

**Comment by PhillZitt** [comment] 2021-02-28 07:42
Duplicate of #3

**Closed as completed by PhillZitt** 2021-02-28 07:42 UTC
Labels: duplicate, wontfix, visual bug
